### ISSUE TITLE
Simulator Times Out

### ISSUE THREAD

**Issue by leifwells** [phonegap/ios-sim#138]
Created the Cordova HelloWorld app using the method here:
http://cordova.apache.org/docs/en/4.0.0/guide_cli_index.md.html#The%20Command-Line%20Interface

When I attempt to run:
cordova run ios

the following happens:

Leifs-MacBook-Pro:hello leifwells$ sudo cordova run ios
Password:
Running command: /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/cordova/run
No device is connected, trying Simulator.
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/emulator
    SDKROOT = iphonesimulator8.1
    VALID_ARCHS = i386
 
=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===
 
Check dependencies
 
=== BUILD TARGET HelloWorld OF PROJECT HelloWorld WITH CONFIGURATION Debug ===
 
Check dependencies
 
PhaseScriptExecution Copy\ www\ directory build/HelloWorld.build/Debug-iphonesimulator/HelloWorld.build/Script-304B58A110DAC018002A0835.sh
    cd /Users/leifwells/Code/phonegap-hello/hello/platforms/ios
    /bin/sh -c /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/HelloWorld.build/Debug-iphonesimulator/HelloWorld.build/Script-304B58A110DAC018002A0835.sh
 
real    0m0.045s
user    0m0.013s
sys     0m0.019s
 
ProcessInfoPlistFile build/emulator/HelloWorld.app/Info.plist HelloWorld/HelloWorld-Info.plist
    cd /Users/leifwells/Code/phonegap-hello/hello/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/leifwells/Code/mongodb-osx-x86_64-2.6.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-infoPlistUtility /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/HelloWorld/HelloWorld-Info.plist -genpkginfo /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/emulator/HelloWorld.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/HelloWorld.build/Debug-iphonesimulator/HelloWorld.build/MainViewController-PartialInfo.plist -o /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/emulator/HelloWorld.app/Info.plist
 
GenerateDSYMFile build/emulator/HelloWorld.app.dSYM build/emulator/HelloWorld.app/HelloWorld
    cd /Users/leifwells/Code/phonegap-hello/hello/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/leifwells/Code/mongodb-osx-x86_64-2.6.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/emulator/HelloWorld.app/HelloWorld -o /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/emulator/HelloWorld.app.dSYM
 
Touch build/emulator/HelloWorld.app
    cd /Users/leifwells/Code/phonegap-hello/hello/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/leifwells/Code/mongodb-osx-x86_64-2.6.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/touch -c /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/build/emulator/HelloWorld.app
 
** BUILD SUCCEEDED **
 
2015-01-12 22:52:45.983 ios-sim[747:30865] stderrPath: /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/cordova/console.log
2015-01-12 22:52:45.984 ios-sim[747:30865] stdoutPath: /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/cordova/console.log
Usage of '--family' is deprecated in 3.x. Use --devicetypeid instead.
Usage of '--retina' is deprecated in 3.x. Use --devicetypeid instead.
Session could not be started: Error Domain=DTiPhoneSimulatorErrorDomain Code=2 "Simulator session timed out." UserInfo=0x7fcc71f1cef0 {NSLocalizedDescription=Simulator session timed out.}
Error: /Users/leifwells/Code/phonegap-hello/hello/platforms/ios/cordova/run: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
Leifs-MacBook-Pro:hello leifwells$

I can run the project from XCode without issue. I have not made any alterations to the HelloWorld code.

Requested Information:
$ sw_vers -productVersion
10.10.1
$ ios-sim --version
3.1.1
$ xcodebuild -version
Xcode 6.1.1
Build version 6A2008a
Leifs-MacBook-Pro:hello leifwells$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
Leifs-MacBook-Pro:hello leifwells$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

**Comment by mokagio** [comment]
Hey @leifwells, I'm not familiar with Cordova, just going through the issues to see if there's something similar to what I'm experiencing. Anyway... did you notice the two errors that `ios-sim` is giving you?

```
Usage of '--family' is deprecated in 3.x. Use --devicetypeid instead.
Usage of '--retina' is deprecated in 3.x. Use --devicetypeid instead.
```

Maybe that could be a good starting point.

**Comment by shazron** [comment]
@leifwells Try shutting down the iOS Simulator and try again. There might be remnants of the simulator process also (see Activity Monitor)
@mokagio That is just a warning, it shouldn't affect things.

**Comment by leifwells** [comment]
I found this thread on the Ionic forums:

http://forum.ionicframework.com/t/issues-emulating-ios/9772

I haven't had a chance to try the various workarounds but wanted to place this link here in case other people run into this issue.

**Comment by shazron** [comment]
Try version 4.x
